name: 适用于 Android 的 Python 3.10.0

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装基础依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev libffi-dev libssl-dev libbz2-dev \
                                 libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
                                 libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
                                 liblzma-dev git tar python3 python3-pip unzip binutils

      - name: 设置 Android NDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: "27.2.12479018"

      - name: 验证 NDK 安装
        run: |
          echo "Android NDK 根目录: $ANDROID_NDK_ROOT"
          ls -l $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/

      - name: 设置交叉编译工具链
        run: |
          export READELF=$(which readelf)
          echo "READELF=$READELF" >> $GITHUB_ENV
          echo "AR=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV
          echo "RANLIB=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib" >> $GITHUB_ENV

      - name: 下载并编译 Python 3.10.0
        run: |
          wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz
          tar -xzf Python-3.10.0.tgz
          cd Python-3.10.0
          
          ./configure \
            --host=aarch64-linux-android \
            --prefix=/data/python \
            --disable-ipv6 \
            CC="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" \
            AR="$AR" \
            RANLIB="$RANLIB"
          
          make -j$(nproc)
          mkdir -p /data/python
          make install

      - name: 打包 Python
        run: |
          tar -czvf python-android-arm64.tar.gz -C /data python

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: python-android-arm64
          path: python-android-arm64.tar.gz
