usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g-O3-Wall -I/home/runner/work/ips/ips/android-vroot/data/python/include -I/home/runner/work/ips/ips/android-vroot/data/python/include -I/home/runner/work/ips/ips/android-vroot/data/python//usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DANDROID   -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-instr-generate -I./包括/内部-I。- 一./包括     -c ./ Modules/grpmodule.c -o Modules/grpmodule.o
./ Modules/grpmodule.c：121：24：warning：unused variable 'buf2' [-Wunused-variable]
  121 |     char *buf = NULL，*buf2 = NULL;
      |                        ^~~~
./ Modules/grpmodule.c：199：24：warning：unused variable 'buf2' [-Wunused-variable]
  199 |     char *buf = NULL，*buf2 = NULL，*name_chars;
      |                        ^~~~
./ Modules/grpmodule.c：281：5：错误类型：调用未声明的函数“setList”; ISO C99 及更高版本不支持隐式函数声明[-Wimplicit-function-declaration]
  281 |     setgrent（）;
      |     ^
./ Modules/grpmodule.c：282：17：错误类型：调用未声明的函数“getInputt”; ISO C99 及更高版本不支持隐式函数声明[-Wimplicit-function-declaration]
  282 |     while（（p = getgrent（））！= NULL）{
      |                 ^
./ Modules/grpmodule.c：282：15：错误：从“int”分配到“struct group *”的整数到指针转换不兼容[-Wint-conversion]
  282 |     while（（p = getgrent（））！= NULL）{
      |               ^ ~~~~~~~~~~
./ Modules/grpmodule.c：287：13：错误类型：调用未声明的函数“endint”; ISO C99 及更高版本不支持隐式函数声明[-Wimplicit-function-declaration]
  287|             endgrent（）；
      |             ^
./ Modules/grpmodule.c：292：5：错误类型：调用未声明的函数“endint”; ISO C99 及更高版本不支持隐式函数声明[-Wimplicit-function-declaration]
  292|     endgrent（）；
      |     ^
生成2个警告和5个错误。
错误 1：[makefile：3063：Modules/grpmodule. o]错误 1：
make[2]：* 正在等待未完成的作业.
make[2]：正在离开目录“/home/runner/work/ips/ips/cpython”
make[1]：* [Makefile：779：profile-gen-stamp]错误 2
make[1]：正在离开目录“/home/runner/work/ips/ips/cpython”
make：* [Makefile：791：profile-run-stamp]错误 2
make 失败
错误：进程已完成，退出代码为% 1。