name: Build Python for Termux (Custom Path)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-python:
    runs-on: ubuntu-latest
    container: termux/package-builder
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: termux/termux-packages
        fetch-depth: 0
        
    - name: Set up build environment
      run: |
        # Create custom installation directory
        sudo mkdir -p /data/python
        sudo chown -R builder:builder /data/python
        
        # Modify Python package definition
        sed -i 's|TERMUX_PREFIX|/data/python|g' packages/python/build.sh
        sed -i 's|--prefix=$TERMUX_PREFIX|--prefix=/data/python|g' packages/python/build.sh
        
        # Install build dependencies
        ./scripts/setup-termux.sh
        
    - name: Build Python package
      run: |
        export TERMUX_PKG_SKIP_SRC_EXTRACT=false
        export TERMUX_PKG_BUILD_IN_SRC=true
        export TERMUX_PREFIX=/data/python
        export PREFIX=$TERMUX_PREFIX
        
        ./build-package.sh -I python
        
    - name: Package artifacts
      run: |
        # Create a tarball of the installation
        tar -czvf python-custom-install.tar.gz -C /data python
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-custom-install
        path: python-custom-install.tar.gz
