name: Build Python for Android (aarch64) - Final Fix

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            wget \
            curl \
            tar \
            xz-utils \
            unzip \
            git \
            tree \
            python3 \
            python3-pip \
            m4 \
            bison \
            flex \
            texinfo \
            gawk \
            libtool \
            autoconf \
            automake \
            pkg-config \
            gperf \
            file

      - name: Setup Android NDK (r27b)
        uses: android-actions/setup-android@v2
        with:
          ndk-version: "27.2.12479018"

      - name: Verify NDK installation
        run: |
          echo "Android NDK root: $ANDROID_NDK_ROOT"
          ls -l $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/
          $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang --version

      - name: Setup cross-compilation tools
        run: |
          export READELF=$(which readelf)
          echo "READELF=$READELF" >> $GITHUB_ENV
          echo "AR=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV
          echo "RANLIB=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib" >> $GITHUB_ENV
          echo "SYSROOT=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot" >> $GITHUB_ENV
          echo "CC=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> $GITHUB_ENV
          echo "CXX=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++" >> $GITHUB_ENV
          echo "ANDROID_API=21" >> $GITHUB_ENV
          echo "CFLAGS_BASE=--sysroot=$SYSROOT -DANDROID -fPIC" >> $GITHUB_ENV
          echo "LDFLAGS_BASE=--sysroot=$SYSROOT -fuse-ld=lld -llog" >> $GITHUB_ENV

      - name: Download source packages
        run: |
          wget https://www.python.org/ftp/python/3.12.8/Python-3.12.8.tar.xz
          wget https://zlib.net/zlib-1.3.1.tar.gz
          wget https://ftp.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz
          wget https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
          wget https://tukaani.org/xz/xz-5.6.2.tar.gz
          
          tar -xf Python-3.12.8.tar.xz && mv Python-3.12.8 cpython
          tar -xzf zlib-1.3.1.tar.gz
          tar -xzf ncurses-6.5.tar.gz
          tar -xzf readline-8.2.tar.gz
          tar -xzf xz-5.6.2.tar.gz

      - name: Build zlib
        run: |
          cd zlib-1.3.1
          ./configure --prefix=/data/python --static
          make -j$(nproc) \
            CC="$CC" \
            AR="$AR" \
            RANLIB="$RANLIB" \
            CFLAGS="$CFLAGS_BASE" \
            LDFLAGS="$LDFLAGS_BASE"
          make install DESTDIR=$GITHUB_WORKSPACE/android-vroot
          cd ..

      - name: Build xz
        run: |
          cd xz-5.6.2
          ./configure \
            --host=aarch64-linux-android \
            --prefix=/data/python \
            --disable-shared \
            --enable-static \
            CC="$CC" \
            AR="$AR" \
            RANLIB="$RANLIB" \
            CFLAGS="$CFLAGS_BASE" \
            LDFLAGS="$LDFLAGS_BASE"
          make -j$(nproc)
          make install DESTDIR=$GITHUB_WORKSPACE/android-vroot
          echo "LZMA_H_PATH=$GITHUB_WORKSPACE/android-vroot/data/python/include" >> $GITHUB_ENV
          echo "LZMA_LIB_PATH=$GITHUB_WORKSPACE/android-vroot/data/python/lib" >> $GITHUB_ENV
          cd ..

      - name: Build ncurses
        run: |
          cd ncurses-6.5
          ./configure \
            --host=aarch64-linux-android \
            --prefix=/data/python \
            --with-shared \
            --without-cxx \
            --without-cxx-binding \
            --without-ada \
            --without-manpages \
            --without-progs \
            --without-tests \
            --with-terminfo-dirs=/data/python/share/terminfo \
            --with-ticlib=no \
            --with-termlib=no \
            --with-termcap \
            CC="$CC" \
            AR="$AR" \
            RANLIB="$RANLIB" \
            CFLAGS="$CFLAGS_BASE" \
            LDFLAGS="$LDFLAGS_BASE"
          make -j$(nproc)
          make install DESTDIR=$GITHUB_WORKSPACE/android-vroot
          
          mkdir -p $GITHUB_WORKSPACE/android-vroot/data/python/lib
          cp -f $GITHUB_WORKSPACE/android-vroot/data/python/lib*/libncurses.* $GITHUB_WORKSPACE/android-vroot/data/python/lib/ || true
          
          echo "READLINE_INCLUDE=$GITHUB_WORKSPACE/android-vroot/data/python/include" >> $GITHUB_ENV
          echo "READLINE_LIB=$GITHUB_WORKSPACE/android-vroot/data/python/lib" >> $GITHUB_ENV
          cd ..

      - name: Build readline (Fixed with manual config)
        run: |
          cd readline-8.2
          
          # Create test program
          cat <<EOF > cross_test.c
          #include <stdio.h>
          #include <android/log.h>
          int main() {
              printf("Cross-compile test running\n");
              __android_log_print(ANDROID_LOG_INFO, "READLINE", "Test passed");
              return 0;
          }
          EOF
          
          # Verify toolchain works
          echo "验证工具链..."
          $CC $CFLAGS_BASE $LDFLAGS_BASE -o cross_test cross_test.c
          file cross_test
          strings cross_test | grep -i "android" || true
          
          # Bypass configure checks
          cat <<EOF > config.cache
          ac_cv_func_sigsetjmp=yes
          ac_cv_func_posix_setjmp=yes
          ac_cv_func_malloc_0_nonnull=yes
          ac_cv_func_realloc_0_nonnull=yes
          bash_cv_wcwidth_broken=no
          ac_cv_prog_cc_works=yes
          ac_cv_prog_cc_cross=yes
          EOF
          
          # Run configure with forced settings
          ./configure \
            --host=aarch64-linux-android \
            --prefix=/data/python \
            --disable-shared \
            --enable-static \
            --cache-file=config.cache \
            CC="$CC" \
            AR="$AR" \
            RANLIB="$RANLIB" \
            CFLAGS="$CFLAGS_BASE -I$READLINE_INCLUDE" \
            LDFLAGS="$LDFLAGS_BASE -L$READLINE_LIB -lncurses" \
            || { echo "configure 可能报错但继续构建..."; }
          
          # Force correct linking
          sed -i 's/^LIBS=.*/LIBS=-lncurses -lc -lm -ldl -llog/' Makefile
          
          make -j$(nproc) || { echo "make 失败，查看错误..."; exit 1; }
          make install DESTDIR=$GITHUB_WORKSPACE/android-vroot
          cd ..

      - name: Configure Python
        run: |
          cd cpython
          export CONFIG_SITE=config.site
          cat <<EOF > $CONFIG_SITE
          ac_cv_file__dev_ptmx=yes
          ac_cv_file__dev_ptc=no
          EOF
          
          ./configure \
            --host=aarch64-linux-android \
            --build=x86_64-linux-gnu \
            --disable-ipv6 \
            --enable-optimizations \
            --with-build-python=$(which python3) \
            --prefix=/data/python \
            CC="$CC" \
            CXX="$CXX" \
            AR="$AR" \
            RANLIB="$RANLIB" \
            READELF="$READELF" \
            CFLAGS="$CFLAGS_BASE -I$LZMA_H_PATH -I$READLINE_INCLUDE" \
            LDFLAGS="$LDFLAGS_BASE -L$LZMA_LIB_PATH -L$READLINE_LIB -llzma -lreadline -lncurses"
          
          make -j$(nproc)
          make install DESTDIR=$GITHUB_WORKSPACE/android-vroot
          cd ..

      - name: Fix installation
        run: |
          # Fix shebangs
          find $GITHUB_WORKSPACE/android-vroot/data/python/bin -type f -exec grep -l '^#!' {} \; | while read -r file; do
            sed -i "1s|.*|#!/data/python/bin/python3|" "$file"
          done
          
          # Fix symlinks
          find $GITHUB_WORKSPACE/android-vroot/data/python -type l | while read -r link; do
            target=$(readlink "$link")
            if [[ "$target" != /* ]]; then
              link_dir=$(dirname "$link")
              abs_target=$(realpath -m "$link_dir/$target")
              new_target="/data/python/${abs_target#*/data/python/}"
              rm "$link"
              ln -s "$new_target" "$link"
            fi
          done
          
          chmod -R 755 $GITHUB_WORKSPACE/android-vroot/data/python/bin

      - name: Package Python
        run: |
          tar -czvf python-3.12.8-android-arm64.tar.gz \
            --transform 's|^android-vroot/||' \
            -C $GITHUB_WORKSPACE/android-vroot \
            data
          tar -tvf python-3.12.8-android-arm64.tar.gz | head -20

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-3.12.8-android-arm64
          path: |
            python-3.12.8-android-arm64.tar.gz
            cpython/config.log
            ncurses-6.5/config.log
            readline-8.2/config.log
            readline-8.2/Makefile

      - name: Debug if failed
        if: failure()
        run: |
          echo "=== 详细诊断 ==="
          echo "1. 工具链验证:"
          $CC --version
          $CC -v 2>&1 | grep "Target:"
          
          echo "2. readline 构建目录内容:"
          ls -la readline-8.2/
          
          echo "3. 关键对象文件检查:"
          file readline-8.2/*.o || true
          
          echo "4. 链接器测试:"
          echo 'void main(){}' > test.c
          $CC $CFLAGS_BASE $LDFLAGS_BASE -v test.c 2>&1 | grep "LIBRARY_PATH"
          
          exit 1
